"""Minimal SO(3)/quaternion utilities used by the dynamics models.

Quaternions use the scalar-first convention ``q = [q_w, q_x, q_y, q_z]``.
Rotation matrices map body-frame vectors to the inertial frame.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


def skew(vector: FloatArray) -> FloatArray:
    """Return the skew-symmetric matrix ``[vector]_x``."""
    x, y, z = np.asarray(vector, dtype=float).reshape(3)
    return np.array(
        [
            [0.0, -z, y],
            [z, 0.0, -x],
            [-y, x, 0.0],
        ],
        dtype=float,
    )


def normalize_quaternion(quaternion: FloatArray) -> FloatArray:
    """Return a normalized scalar-first quaternion."""
    quaternion = np.asarray(quaternion, dtype=float).reshape(4)
    norm = np.linalg.norm(quaternion)
    if norm <= np.finfo(float).eps:
        raise ValueError("quaternion norm must be nonzero.")
    return quaternion / norm


def rotation_matrix_from_quaternion(quaternion: FloatArray) -> FloatArray:
    """Return the body-to-inertial rotation matrix for a scalar-first quaternion."""
    qw, qx, qy, qz = normalize_quaternion(quaternion)

    return np.array(
        [
            [
                1.0 - 2.0 * (qy * qy + qz * qz),
                2.0 * (qx * qy - qw * qz),
                2.0 * (qx * qz + qw * qy),
            ],
            [
                2.0 * (qx * qy + qw * qz),
                1.0 - 2.0 * (qx * qx + qz * qz),
                2.0 * (qy * qz - qw * qx),
            ],
            [
                2.0 * (qx * qz - qw * qy),
                2.0 * (qy * qz + qw * qx),
                1.0 - 2.0 * (qx * qx + qy * qy),
            ],
        ],
        dtype=float,
    )


def quaternion_derivative_body_rates(
    quaternion: FloatArray,
    angular_velocity_body: FloatArray,
) -> FloatArray:
    """Quaternion derivative generated by body-frame angular velocity.

    Implements ``q_dot = 0.5 * q \\otimes [0, omega]`` for scalar-first
    quaternions.
    """
    qw, qx, qy, qz = normalize_quaternion(quaternion)
    wx, wy, wz = np.asarray(angular_velocity_body, dtype=float).reshape(3)

    return 0.5 * np.array(
        [
            -(qx * wx + qy * wy + qz * wz),
            qw * wx + qy * wz - qz * wy,
            qw * wy + qz * wx - qx * wz,
            qw * wz + qx * wy - qy * wx,
        ],
        dtype=float,
    )


def quaternion_to_roll_pitch_yaw(quaternion: FloatArray) -> tuple[float, float, float]:
    """Convert a scalar-first quaternion to ZYX roll, pitch, and yaw."""
    qw, qx, qy, qz = normalize_quaternion(quaternion)

    sin_roll_cos_pitch = 2.0 * (qw * qx + qy * qz)
    cos_roll_cos_pitch = 1.0 - 2.0 * (qx * qx + qy * qy)
    roll = float(np.arctan2(sin_roll_cos_pitch, cos_roll_cos_pitch))

    sin_pitch = 2.0 * (qw * qy - qz * qx)
    pitch = float(np.arcsin(np.clip(sin_pitch, -1.0, 1.0)))

    sin_yaw_cos_pitch = 2.0 * (qw * qz + qx * qy)
    cos_yaw_cos_pitch = 1.0 - 2.0 * (qy * qy + qz * qz)
    yaw = float(np.arctan2(sin_yaw_cos_pitch, cos_yaw_cos_pitch))

    return roll, pitch, yaw


def quaternion_from_roll_pitch_yaw(
    roll: float,
    pitch: float,
    yaw: float,
) -> FloatArray:
    """Return a scalar-first quaternion for ZYX roll, pitch, and yaw.

    The returned quaternion maps body-frame vectors to the inertial frame and
    is the inverse operation of :func:`quaternion_to_roll_pitch_yaw` away from
    the usual Euler-angle singularities.
    """
    half_roll = 0.5 * float(roll)
    half_pitch = 0.5 * float(pitch)
    half_yaw = 0.5 * float(yaw)

    cr = np.cos(half_roll)
    sr = np.sin(half_roll)
    cp = np.cos(half_pitch)
    sp = np.sin(half_pitch)
    cy = np.cos(half_yaw)
    sy = np.sin(half_yaw)

    return normalize_quaternion(
        np.array(
            [
                cr * cp * cy + sr * sp * sy,
                sr * cp * cy - cr * sp * sy,
                cr * sp * cy + sr * cp * sy,
                cr * cp * sy - sr * sp * cy,
            ],
            dtype=float,
        )
    )
